name: Python application lint and test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pytest
        pip install pytest-cov
        pip install mypy==1.5.1
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Type checker
      run: |
        mypy --strict src
    - name: Run Pylint
      run: |
          pylint --enable=all **/*.py
    - name: Test with pytest
      run: |
        pytest --cov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}